### ISSUE TITLE
performance problem due to passing matrices by value

### ISSUE THREAD

**Issue by jfhg** [unicredit/linear-algebra#8]
First I'd like to thank for your effort creating linear algebra library for Nim!
As an experiment I rewrote Michael Nielson's neural network Python/numpy example code in Nim (https://github.com/jfhg/nimdeep).
The simple implementation using DMatrix64 as in the repository was pretty slow.
It turned out that changing DMatrix64 to `ref object of RootObj` in my local linalg copy made things fast as expected.
Shouldn't matrices be passed by reference generally?

**Comment by andreaferretti** [comment]
Hi, first of all thank you for trying it out! I have been wanting to write a neural network library for a while now, but I never managed to find the time. I hope your experiment will expand into one! :-)

About passing matrices by value: you are right. In fact, if you see, I have a `ref` to the actual data for the types `Matrix32` and `Matrix64`. For the dynamic version, I wanted to use plain `seq`s for the vectors, and I ended up putting plain `seq`s into the matrix types as well.

Now, the thing is, `seq` in Nim is just a type holding a length and a `ref` to the actual data. **But** Nim insists in having a value semantics, which means that assignment for `seq` will perform an actual copy of the data, unlike if you wrote your custom type

``` nim
type MySeq[A] = object
  len: int
  data: ptr[A]
```

I was aware of this, hence I used `shallowCopy` instead of plain assignment in quite a few places such as [here](https://github.com/unicredit/linear-algebra/blob/master/private/trivial_ops.nim#L85-L86).

Still, I guess this creates problems to users - just passing a matrix can result in copies, which I would not want.

I guess I could just put a ref to the data inside the matrix type. Do you already have a version with the necessary changes?

By the way, I would not use `of RootObj` here. This is used for inheritance and has nothing to do with passing a reference or a copy; moreover it modifies the layout in memory (there is some additional type tag prepended or something) so just using `ref` is fine.

**Comment by jfhg** [comment]
I have something hacked together that works for my case. I can make a proper PR in the next days.
